### ISSUE TITLE
Clarify how to pass JSON through argv

### ISSUE THREAD

**Issue by markstos** [briancsparks/ra-ecosystem#1]
Some Lambda's need a nested object structure as input. The docs here only show simple name/value pairs.

Also, `process.argv` always passes through values as strings, but a Lambda event may expect values as booleans or Numbers. How will RA address this? 

This can especially important for `--foo=false`, which would be turned into the string "false", which values to `true` when cast back to a boolean.

**Comment by markstos** [comment]
As reference, the `serverless` framework has a "Invoke Local" feature to allow Lambda functions to be run the CLI. They solve this problem by not trying to convert argv into a JavaScript object. Instead, they provide `--data` and `--path` so JSON can be passed as a string or as a file. That design addresses both the nesting issue and the casting issue. 

Serverless also supports running Express apps without changing your code:
https://github.com/awslabs/aws-serverless-express

**Comment by briancsparks** [comment]
RA now has `invoke2`, in addition to `invoke`. When invoke2 is used, RA uses the sg-argv module to parse the arguments, which has much more intelligent capabilities: including awareness of true, false, and null; parsing JSON, and reading files (including '.json' files.)
